spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default
    username: username
    password: pass123

custom:
  datasource:
    enabled : true

management:
  endpoints:
    web:
      exposure:
        include: health, appInfo